catalog/urls.py
"""This contains all of the URL mappings for the catalog application. The `urlpatterns` list
routes URLs to views. For more information please see:

    https://docs.djangoproject.com/en/2.1/topics/http/urls/
"""

from . import views
from django.conf.urls import include
from django.urls import path, re_path


# URLs for the basic domain views
urlpatterns = [
    path('', views.index, name='index'),
    path('domains/', views.DomainListView.as_view(), name='domains'),
    path('avail_domains/', views.AvailDomainListView.as_view(), name='available-domains'),
    path('active_domains/', views.ActiveDomainListView.as_view(), name='active-domains'),
    path('res_domains/', views.ResDomainListView.as_view(), name='reserved-domains'),
    path('graveyard/', views.GraveyardListView.as_view(), name='graveyard'),
    path('domain/<int:pk>', views.DomainDetailView.as_view(), name='domain-detail'),
    path('mydomains/', views.ActiveDomainsByUserListView.as_view(), name='my-domains'),
    path('error/', views.error, name='error'),
    path('profile/', views.profile, name='profile'),
]

# URLs for creating, updating, and deleting project histories
urlpatterns += [
    path('history/<int:pk>/create/', views.HistoryCreate.as_view(), name='history_create'),
    path('history/<int:pk>/update/', views.HistoryUpdate.as_view(), name='history_update'),
    path('history/<int:pk>/delete/', views.HistoryDelete.as_view(), name='history_delete'),
]

# URLs for creating, updating, and deleting domains
urlpatterns += [
    path('domain/create/', views.DomainCreate.as_view(), name='domain_create'),
    path('domain/<int:pk>/update/', views.DomainUpdate.as_view(), name='domain_update'),
    path('domain/<int:pk>/delete/', views.DomainDelete.as_view(), name='domain_delete'),
]

# URLs for domain status change functions
urlpatterns += [
    path('checkout/<int:pk>', views.checkout, name='checkout'),
    path('release/<int:pk>', views.release, name='release'),
]

# URLs for management functions
urlpatterns += [
    path('management/', views.management, name='management'),
    path('update/', views.update, name='update'),
    path('update_dns/', views.update_dns, name='update_dns'),
    path('upload/csv/', views.upload_csv, name='upload_csv'),
]

shepherd/urls.py
"""This contains all of the URL mappings for the main Shepherd application. The `urlpatterns` list
routes URLs to views. For more information please see:

    https://docs.djangoproject.com/en/2.1/topics/http/urls/
"""

from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
"""This contains all of the database models for the catalog application."""

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

import datetime
from datetime import date


class HealthStatus(models.Model):
    """Model representing the available domain health settings."""
    health_status = models.CharField(max_length=20, unique=True, help_text='Health status type (e.g. Healthy, Burned)')

    class Meta:
        """Metadata for the model."""
        ordering = ['health_status']
        verbose_name = 'Health status'
        verbose_name_plural = 'Health statuses'
    
    def __str__(self):
        """String for representing the model object (in Admin site etc.)."""
        return self.health_status


class DomainStatus(models.Model):
    """Model representing the available domain statuses."""
    domain_status = models.CharField(max_length=20, unique=True, help_text='Domain status type (e.g. Available)')

    class Meta:
        """Metadata for the model."""
        ordering = ['domain_status']
        verbose_name = 'Domain status'
        verbose_name_plural = 'Domain statuses'
    
    def __str__(self):
        """String for representing the model object (in Admin site etc.)."""
        return self.domain_status


class WhoisStatus(models.Model):
    """Model representing the available WHOIS privacy statuses."""
    whois_status = models.CharField(max_length=20, unique=True, help_text='WHOIS privacy status (e.g. Enabled, Disabled)')

    class Meta:
        """Metadata for the model."""
        ordering = ['whois_status']
        verbose_name = 'WHOIS status'
        verbose_name_plural = 'WHOIS statuses'
    
    def __str__(self):
        """String for representing the model object (in Admin site etc.)."""
        return self.whois_status


class ActivityType(models.Model):
    """Model representing the available domain activity types."""
    activity = models.CharField(max_length=100, unique=True, help_text='Enter a reason for the use of the domain (e.g. command-and-control)')

    class Meta:
        """Metadata for the model."""
        ordering = ['activity']
        verbose_name = 'Domain activity'
        verbose_name_plural = 'Domain activities'
    
    def __str__(self):
        """String for representing the model object (in Admin site etc.)."""
        return self.activity


class ProjectType(models.Model):
    """Model representing the available project types."""
    project_type = models.CharField('Project Type', max_length=100, unique=True, help_text='Enter a project type (e.g. red team, penetration test)')

    class Meta:
        """Metadata for the model."""
        ordering = ['project_type']
        verbose_name = 'Project type'
        verbose_name_plural = 'Project types'
    
    def __str__(self):
        """String for representing the model object (in Admin site etc.)."""
        return self.project_type


class Client(models.Model):
    """Model representing the clients attached to project records. This model tracks client
    information. Addition details can be added beyond the client's name, but it likely
    unnecessary for the catalog.
    """
    name = models.CharField('Client Name', max_length=100, unique=True, help_text='Enter the name of the client')

    class Meta:
        """Metadata for the model."""
        ordering = ['name']
        verbose_name = 'Client'
        verbose_name_plural = 'Clients'
    
    def __str__(self):
        """String for representing the model object (in Admin site etc.)."""
        return self.name


class Domain(models.Model):
    """Model representing the domains and related information. This is the primary model for the
    catalog application. This model keeps a record of the domain name and the domain's health,
    categories, and current status (e.g. Available).

    The availability and health statuses are Foreign Keys.
    """
    name = models.CharField('Name', max_length=100, unique=True, help_text='Enter a domain name')
    registrar = models.CharField('Registrar', max_length=100, unique=True, help_text='Enter the name of the registrar where this domain is registered', null=True)
    dns_record = models.CharField('DNS Record', max_length=500, help_text='Enter domain DNS records', null=True)
    health_dns = models.CharField('DNS Health', max_length=100, help_text='Domain health status based on passive DNS (e.g. Healthy, Burned)', null=True)
    creation = models.DateField('Purchase Date', help_text='Domain purchase date')
    expiration = models.DateField('Expiration Date', help_text='Domain expiration date')
    all_cat = models.TextField('All Categories', help_text='All categories applied to this domain', null=True)
    ibm_xforce_cat = models.CharField('IBM X-Force', max_length=100, help_text='Domain category as determined by IBM X-Force', null=True)
    talos_cat = models.CharField('Cisco Talos', max_length=100, help_text='Domain category as determined by Cisco Talos', null=True)
    bluecoat_cat =models.CharField('Bluecoat', max_length=100, help_text='Domain category as determined by Bluecoat', null=True)
    fortiguard_cat = models.CharField('Fortiguard', max_length=100, help_text='Domain category as determined by Fortiguard', null=True)
    opendns_cat = models.CharField('OpenDNS', max_length=100, help_text='Domain category as determined by OpenDNS', null=True)
    trendmicro_cat = models.CharField('TrendMicro', max_length=100, help_text='Domain category as determined by TrendMicro', null=True)
    mx_toolbox_status =  models.CharField('MX Toolbox Status', max_length=100, help_text='Domain spam status as determined by MX Toolbox', null=True)
    note = models.TextField('Notes', help_text='Domain-related notes, such as thoughts behind its purchase or how/why it was burned or retired', null=True)
    burned_explanation = models.TextField('Health Explanation', help_text='Reasons why the domain\'s health status is not "Healthy"', null=True)
    # Foreign Keys
    whois_status = models.ForeignKey('WhoisStatus', on_delete=models.PROTECT, null=True)
    health_status = models.ForeignKey('HealthStatus', on_delete=models.PROTECT, null=True)
    domain_status = models.ForeignKey('DomainStatus', on_delete=models.PROTECT, null=True)
    last_used_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        """Metadata for the model."""
        ordering = ['health_status', 'name']
        permissions = (('can_retire_domain', 'Can retire a domain'), ('can_mark_reserved', 'Can reserve a domain'),)
        verbose_name = 'Domain'
        verbose_name_plural = 'Domains'

    def get_absolute_url(self):
        """Returns the URL to access a particular instance of the model."""
         # Adds a "View on Site" button to the model's record editing screens in the Admin site
        return reverse('domain-detail', args=[str(self.id)])

    def get_domain_age(self):
        """Calculate the domain's age based on the current date and the domain's purchase date."""
        time_delta = datetime.date.today() - self.creation
        return time_delta.days

    @property
    def get_list(self):
        """Property to enable fetching the list from the dns_record entry."""
        if self.dns_record:
            return self.dns_record.split(' ::: ')
        else:
            None
    
    def __str__(self):
        """String for representing the model object (in Admin site etc.)."""
        return f'{self.name} ({self.health_status})'


class History(models.Model):
    """Model representing the project history. This model records start and end dates for a project
    and then uses Foreign Keys for linking the dates to a client, project type, activity type, and
    domain.
    """
    # This field is automatically filled with the current date at check-out
    start_date = models.DateField('Start Date', auto_now_add=True, max_length=100, help_text='Enter the start date of the project')
    end_date = models.DateField('End Date', max_length=100, help_text='Enter the end date of the project')
    note = models.TextField('Notes', help_text='Project-related notes, such as how the domain will be used/how it worked out', null=True)
    slack_channel =  models.CharField('Project Slack Channel', max_length=100, help_text='Name of the Slack channel to be used for updates for this domain during the project\'s duration', null=True)
    # Foreign Keys
    client = models.ForeignKey('Client', on_delete=models.CASCADE, null=False)
    domain = models.ForeignKey('Domain', on_delete=models.CASCADE, null=False)
    operator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    project_type = models.ForeignKey('ProjectType', on_delete=models.PROTECT, null=False)
    activity_type = models.ForeignKey('ActivityType', on_delete=models.PROTECT, null=False, blank=True)

    class Meta:
        """Metadata for the model."""
        ordering = ['client', 'domain']
        verbose_name = 'Historical project'
        verbose_name_plural = 'Historical projects'

    def get_absolute_url(self):
        """Returns the URL to access a particular instance of the model."""
         # Adds a "View on Site" button to the model's record editing screens in the Admin site
        return reverse('history_update', args=[str(self.id)])

    def __str__(self):
        """String for representing the model object (in Admin site etc.)."""
        return f'{self.client} {self.project_type.project_type} - {self.domain.name} ({self.activity_type.activity}) {self.start_date} to {self.end_date} - {self.operator}'

    @property
    def is_overdue(self):
        """Property to test if the provided end date is in the past."""
        if self.start_date and date.today() > self.end_date:
            return True
        return False

catalog/forms.py
"""This contains all of the forms for the catalog application."""

import datetime

from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from catalog.models import Domain, HealthStatus, DomainStatus, ActivityType, ProjectType, Client, History


class DateInput(forms.DateInput):
    input_type = 'date'


class CheckoutForm(forms.Form):
    """Form used for domain checkout. Updates the domain (status) and creates a project entry."""
    client = forms.ModelChoiceField(queryset=Client.objects.all(), to_field_name='name', help_text='Select the client.')
    start_date = forms.DateField(help_text='Select a start date for the project.')
    end_date = forms.DateField(help_text='Select an end  date for the project.')
    project_type = forms.ModelChoiceField(queryset=ProjectType.objects.all(), to_field_name='project_type', help_text='Select the type of project.')
    activity = forms.ModelChoiceField(queryset=ActivityType.objects.all(), to_field_name='activity', help_text='Select how this domain will be used.')
    note = forms.CharField(help_text='Enter a note, such as how this domain will be used.', widget=forms.Textarea, required=False)
    slack_channel = forms.CharField(help_text='Enter a Slack channel with the hashtag where notifications can be sent (e.g. #shepherd, with the hashtag).', required=False)

    class Meta:
        widgets = {
                    'start_date': forms.DateInput(attrs={'id': 'datepicker'}),
                    'end_date': forms.DateInput(attrs={'class': 'datepicker'})
                  }

    def clean_end_date(self):
        """Clean and sanitize user input."""
        data = self.cleaned_data['end_date']
        # Check if a date is not in the past. 
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date: The provided end date is in past'))
        # Return the cleaned data.
        return data


class DomainCreateForm(forms.ModelForm):
    """Form used with the DomainCreate CreateView in models.py to allow excluding fields."""
    class Meta:
        """Metadata for the model form."""
        model = Domain
        exclude = ('last_used_by', 'burned_explanation')
        widgets = {
                    'creation': DateInput(),
                    'expiration': DateInput()
                  }

catalog/templates/catalog/active_domains_user.html
{% extends "base_generic.html" %}

{% block pagetitle %}Your Checked-out Domains{% endblock %}

{% block content %}
    <h2>Active Domains for {{ request.user.get_username }}</h2>
    {% if history_list %}
        <p>The following domains are currently checked-out for your account:</p>
        <br />
        <table>
            <tr>
                <th>Domain</th>
                <th>Check-in Date</th>
                <th>Health</th>
                <th>DNS Health</th>
                <th>Whois Privacy</th>
                <th>Notes</th>
                <th style="text-align: center">Release</th>
            </tr>
            {% for entry in history_list %}
                <tr>
                    <td><a href="{{ entry.domain.get_absolute_url }}">{{ entry.domain.name }}</a></td>

                    <td class="{% if entry.is_overdue %}text-danger{% endif %}">{{ entry.end_date }}</td>

                    {% if entry.domain.health_status.health_status == "Healthy" %}
                        <td style="color: green">{{ entry.domain.health_status }}</td>
                    {% else %}
                        <td style="color: red">{{ entry.domain.health_status }}</td>
                    {% endif %}

                    {% ifequal entry.domain.health_dns "Healthy" %}
                        <td style="color: green">{{ entry.domain.health_dns }}</td>
                    {% else %}
                        <td style="color: red">{{ entry.domain.health_dns }}</td>
                    {% endifequal %}

                    {% ifequal entry.domain.whois_status.whois_status "Enabled" %}
                        <td style="color: green">{{ entry.domain.whois_status }}</td>
                    {% else %}
                        <td style="color: red">{{ entry.domain.whois_status }}</td>
                    {% endifequal %}

                    <td>{{ entry.domain.note }}</td>

                    <td style="text-align: center"><a href="{% url 'release' entry.domain.id %}" class="button">Release</a></td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>There are no domains currently checked-out for your account.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/available_domains.html
{% extends "base_generic.html" %}

{% block pagetitle %}Available Domains, Pick Carefully{% endblock %}

{% block content %}
    <h2>Available Domains</h2>
    {% if domain_list %}
        <p>The following domains are available today:</p>
        <br />
        <table>
            <tr>
                <th>Domain</th>
                <th>Status</th>
                <th>Health</th>
                <th>DNS Health</th>
                <th>Whois Privacy</th>
                <th>Purchase Date</th>
                <th>Notes</th>
                <th style="text-align: center">Check-out</th>
            </tr>
            {% for domain in domain_list %}
                <tr>
                    <td><a href="{{ domain.get_absolute_url }}">{{ domain.name }}</a></td>

                    {% if domain.domain_status.domain_status == "Available" %}
                        <td style="color: green">{{ domain.domain_status }}</td>
                    {% else %}
                        <td style="color: red">{{ domain.domain_status }}</td>
                    {% endif %}

                    {% if domain.health_status.health_status == "Healthy" %}
                        <td style="color: green">{{ domain.health_status }}</td>
                    {% else %}
                        <td style="color: red">{{ domain.health_status }}</td>
                    {% endif %}

                    {% ifequal domain.health_dns "Healthy" %}
                        <td style="color: green">{{ domain.health_dns }}</td>
                    {% else %}
                        <td style="color: red">{{ domain.health_dns }}</td>
                    {% endifequal %}

                    {% ifequal domain.whois_status.whois_status "Enabled" %}
                        <td style="color: green">{{ domain.whois_status }}</td>
                    {% else %}
                        <td style="color: red">{{ domain.whois_status }}</td>
                    {% endifequal %}

                    <td>{{ domain.creation }}</td>
                    <td>{{ domain.note }}</td>

                    {% if domain.domain_status.domain_status == "Available" %}
                        <td style="text-align: center"><a href="{% url 'checkout' domain.id %}" class="button">Check-out</button></td>
                    {% else %}
                        <td style="text-align: center">This domain is unavailable.</td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>There are no domains marked as available. Time for some shopping!</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/checkout.html
{% extends "base_generic.html" %}

{% block pagetitle %}Domain Check-out{% endblock %}

{% block content %}
    <style>
        th {
            background-color: #fafafa;
            color: black;
        }
        th:hover {background-color:#f5f5f5;}
    </style>
    <h2>Checking-out: {{ domain_name }}</h2>
    <p>Complete this form and then click Save:</p>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <br />
        <input type="submit" class="button" value="Save">
    </form>

    <!-- Script for Datepicker -->
    <script>
        $(function() {
            $("#id_start_date").datepicker();
            $("#id_end_date").datepicker();
        });
    </script>
{% endblock %}

catalog/templates/catalog/domain_detail.html
{% extends "base_generic.html" %}

{% block pagetitle %}{{ domain.name }} details{% endblock %}

{% block content %}
    <h2>{{ domain.name }}</h2>
    <p style="font-size: 15px">
        {% load check_group %}
        {% if request.user|has_group:"Senior Operators" %}
            <a href="{% url 'domain_update' domain.id %}">[Edit]</a>
            <a href="#">  [Reserve]</a>
        {% endif %}
    </p>
    <div style="margin-left:20px;margin-top:20px">
        <br /><br />
        <h4>Current Status</h4>
        <table>
            <tr>
                <th>Status</th>
                <th>Health</th>
                <th>DNS Health</th>
                <th>Whois Privacy</th>
                <th>Age</th>
                <th>Notes</th>
            </tr>
            <tr>
                {% if domain.domain_status.domain_status == "Available" %}
                    <td style="color: green">{{ domain.domain_status }}</td>
                {% else %}
                    <td style="color: red">{{ domain.domain_status }}</td>
                {% endif %}

                {% if domain.health_status.health_status == "Healthy" %}
                    <td style="color: green">{{ domain.health_status }}</td>
                    {% else %}
                    <td style="color: red">{{ domain.health_status }}</td>
                {% endif %}

                {% ifequal domain.health_dns "Healthy" %}
                    <td style="color: green">{{ domain.health_dns }}</td>
                {% else %}
                    <td style="color: red">{{ domain.health_dns }}</td>
                {% endifequal %}

                {% ifequal domain.whois_status.whois_status "Enabled" %}
                    <td style="color: green">{{ domain.whois_status }}</td>
                {% else %}
                    <td style="color: red">{{ domain.whois_status }}</td>
                {% endifequal %}

                <td>{{ domain.get_domain_age }} days</td>
                <td>{{ domain.note }}</td>
            </tr>
        </table>
        <br /><br />

        {% if domain.burned_explanation %}
            <h4>Health Explanation</h4>
            <table>
                <tr>
                    <th>Reasons</th>
                </tr>
                <tr>
                    <td>{{ domain.burned_explanation }}</td>
                </tr>
            </table>
        {% endif %}

        <h4>DNS Records</h4>
        <table>
            <tr>
                <th>Records</th>
            </tr>
            {% for record in domain.get_list %}
            <tr>
                <td>{{ record }}</td>
            </tr>
            {% endfor %}
        </table>

        <br /><br />
        <h4>Categories</h4>
        <table>
            <tr>
                <th>All Categories</th>
                <th>IBM X-Force</th>
                <th>Cisco Talos</th>
                <th>Bluecoat</th>
                <th>Fortiguard</th>
                <th>OpeDNS</th>
                <th>TrendMicro</th>
                <th>MX Toolbox</th>
            </tr>
            <tr>
                <td>{{ domain.all_cat }}</td>
                <td>{{ domain.ibm_xforce_cat }}</td>
                <td>{{ domain.talos_cat }}</td>
                <td>{{ domain.bluecoat_cat }}</td>
                <td>{{ domain.fortiguard_cat }}</td>
                <td>{{ domain.opendns_cat }}</td>
                <td>{{ domain.trendmicro_cat }}</td>
                <td>{{ domain.mx_toolbox_status }}</td>
            </tr>
        </table>

        <br /><br />
        <h4>Project History</h4>
        {% if domain.history_set.all %}
            <table>
                <tr>
                    <th>Client</th>
                    <th>Activity Type</th>
                    <th>Project Type</th>
                    <th>Start</th>
                    <th>End</th>
                    <th>Operator</th>
                    <th>Note</th>
                    <th style="text-align:center">Edit</th>
                </tr>
                {% for project in domain.history_set.all %}
                    <tr>
                        <td>{{ project.client }}</td>
                        <td>{{ project.activity_type }}</td>
                        <td>{{ project.project_type }}</td>
                        <td>{{ project.start_date }}</td>
                        <td>{{ project.end_date }}</td>
                        <td>{{ project.operator }}</td>
                        <td>{{ project.note }}</td>
                        <td style="text-align:center"><a href="{% url 'history_update' project.id %}" class="button">Edit</a></td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <p>This domain has no history.</p>
        {% endif %}
        </div>
{% endblock %}

catalog/templates/catalog/domain_form.html
{% extends "base_generic.html" %}

{% block pagetitle %}Domain Entry{% endblock %}

{% block content %}
    <style>
        th {
            background-color: #fafafa;
            color: black;
        }
        th:hover {background-color:#f5f5f5;}
    </style>
    <h2>Create Individual Domain</h2>
    <p>Use this form to create a single domain:</p>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <br />
        <input type="submit" class="button" value="Submit">
    </form>
{% endblock %}

catalog/templates/catalog/graveyard.html
{% extends "base_generic.html" %}

{% block pagetitle %}The Graveyard, Home of Domains Past{% endblock %}

{% block content %}
    <h2>The Graveyard</h2>
    {% if domain_list %}
        <p>Visit domains from the past who are now at rest:</p>
        <br />
        <table>
            <tr>
                <th>Domain</th>
                <th>Status</th>
                <th>Health</th>
                <th>DNS Health</th>
                <th>Whois Privacy</th>
                <th>Purchase Date</th>
                <th>Notes</th>
            </tr>
            {% for domain in domain_list %}
                <tr>
                    <td><a href="{{ domain.get_absolute_url }}">{{ domain.name }}</a></td>

                    {% if domain.domain_status.domain_status == "Available" %}
                        <td style="color: green">{{ domain.domain_status }}</td>
                    {% else %}
                        <td style="color: red">{{ domain.domain_status }}</td>
                    {% endif %}

                    {% if domain.health_status.health_status == "Healthy" %}
                        <td style="color: green">{{ domain.health_status }}</td>
                    {% else %}
                        <td style="color: red">{{ domain.health_status }}</td>
                    {% endif %}

                    {% ifequal domain.health_dns "Healthy" %}
                        <td style="color: green">{{ domain.health_dns }}</td>
                    {% else %}
                        <td style="color: red">{{ domain.health_dns }}</td>
                    {% endifequal %}

                    {% ifequal domain.whois_status.whois_status "Enabled" %}
                        <td style="color: green">{{ domain.whois_status }}</td>
                    {% else %}
                        <td style="color: red">{{ domain.whois_status }}</td>
                    {% endifequal %}

                    <td>{{ domain.creation }}</td>

                    <td>{{ domain.note }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>There are no domains marked as burned yet. Good work?</p>
    {% endif %}
    {% load static %}
    <div style="margin:35px;">
        <img src="{% static 'images/tombstone.png' %}" alt="SpecterOps Logo" style="width:15%;">
    </div>
{% endblock %}

catalog/templates/catalog/reserved_domains.html
{% extends "base_generic.html" %}

{% block pagetitle %}Reserved Domains, the Domain Waiting Room{% endblock %}

{% block content %}
    <h2>Reserved Domains</h2>
    {% if domain_list %}
        <p>The following domains have been flagged as "Reserved" are are temporarily unavailable for projects:</p>
        <table>
            <tr>
                <th>Domain</th>
                <th>Status</th>
                <th>Health</th>
                <th>DNS Health</th>
                <th>Whois Privacy</th>
                <th>Purchase Date</th>
                <th>Notes</th>
                <th style="text-align: center">Release</th>
            </tr>
            {% for domain in domain_list %}
                <tr>
                    <td><a href="{{ domain.get_absolute_url }}">{{ domain.name }}</a></td>

                    <td>{{ domain.domain_status }}</td>

                    {% if domain.health_status.health_status == "Healthy" %}
                        <td style="color: green">{{ domain.health_status }}</td>
                    {% else %}
                        <td style="color: red">{{ domain.health_status }}</td>
                    {% endif %}

                    {% ifequal domain.health_dns "Healthy" %}
                        <td style="color: green">{{ domain.health_dns }}</td>
                    {% else %}
                        <td style="color: red">{{ domain.health_dns }}</td>
                    {% endifequal %}

                    {% ifequal domain.whois "Enabled" %}
                        <td style="color: green">{{ domain.whois }}</td>
                    {% else %}
                        <td style="color: red">{{ domain.whois }}</td>
                    {% endifequal %}

                    <td>{{ domain.creation }}</td>
                    <td>{{ domain.note }}</td>

                    {% if perms.catalog.can_mark_reserved %}
                        <td style="text-align: center"><button class="button">Release</button></td>
                    {% else %}
                        <td style="text-align: center">You are not authorized to release domains</td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>There are no reserved domains.</p>
    {% endif %}
{% endblock %}
 